# Generated by Django 2.1 on 2018-09-21 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coinpair',
            name='percent_change_1h',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='coinpair',
            name='percent_change_24h',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='coinpair',
            name='percent_change_7d',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='coinpair',
            name='price_usd',
            field=models.FloatField(default=0.0),
        ),
    ]
