# Generated by Django 2.1 on 2018-09-21 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coin', '0002_auto_20180921_0735'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coinpair',
            name='percent_change_1h',
        ),
        migrations.RemoveField(
            model_name='coinpair',
            name='percent_change_24h',
        ),
        migrations.RemoveField(
            model_name='coinpair',
            name='percent_change_7d',
        ),
        migrations.RemoveField(
            model_name='coinpair',
            name='price_usd',
        ),
        migrations.AddField(
            model_name='coin',
            name='percent_change_1h',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='coin',
            name='percent_change_24h',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='coin',
            name='percent_change_7d',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='coin',
            name='price_usd',
            field=models.FloatField(default=0.0),
        ),
    ]
