version: '3'

services:
  db:
    restart: unless-stopped
    image: postgres
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    image: "redis:4"
    restart: unless-stopped
    hostname: redis
    expose:
      - "6379"

  rabbit:
    hostname: rabbit
    restart: unless-stopped
    image: rabbitmq:3-management
    env_file:
      - .env
    ports:
      - "5672:5672"  # we forward this port because it's useful for debugging
      - "15672:15672"  # here, we can access rabbitmq management plugin

  backend:
    restart: unless-stopped
    build:
      context: ./backend
      dockerfile: Dockerfile.backend
    volumes:
      - ./backend:/code
    ports:
      - "80:8000"
      - "3000:3000"
    env_file:
      - .env
    command: ["/code/wait-for-postgres.sh", "db", "/code/init.sh"]
    depends_on:
      - db
      - rabbit
      - redis

  worker:
    restart: unless-stopped
    build:
      context: ./backend
      dockerfile: Dockerfile.worker
    volumes:
     - ./backend:/code
    env_file:
     - .env
    #command: ["/code/wait-for-postgres.sh", "db", "/code/run-celery.sh"]
    depends_on:
     - db
     - rabbit
     - redis
    tty: true

volumes:
  db_data: