version: '3'

services:
  db:
    restart: unless-stopped
    image: postgres
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    image: "redis:4"
    restart: unless-stopped
    hostname: redis
    expose:
      - "6379"

  rabbit:
    hostname: rabbit
    restart: unless-stopped
    image: rabbitmq:3-management
    env_file:
      - .env
    expose:
      - "5672"  # we forward this port because it's useful for debugging
      - "15672"  # here, we can access rabbitmq management plugin

  backend: &backend
    restart: unless-stopped
    build:
      context: ./backend
      dockerfile: Dockerfile.backend
    volumes:
      - ./backend:/code
      - static:/static
    expose:
      - "8000"
    env_file:
     - .env.prod
    command: ["/code/wait-for-postgres.sh", "db", "/code/init.sh"]
    depends_on:
      - db
      - rabbit
      - redis

  celery:
    restart: unless-stopped
    <<: *backend
    volumes:
     - ./backend:/code
    env_file:
     - .env.prod
    command: ["/code/wait-for-postgres.sh", "db", "/code/run-celery.sh"]
    depends_on:
     - db
     - rabbit
     - redis
    tty: true

  daphne:
    <<: *backend
    command: ["/code/wait-for-postgres.sh", "db", "/code/start-daphne.sh"]
    expose:
      - "8001"
    depends_on:
      - db
      - redis

  worker:
    <<: *backend
    command: ["/code/wait-for-postgres.sh", "db", "/code/start-worker.sh"]
    depends_on:
      - db
      - redis

  nginx:
    restart: unless-stopped
    container_name: nginx_server
    build:
      context: ./nginx/
      dockerfile: Dockerfile
    depends_on:
      - backend
      - daphne
      - worker
    volumes:
      - static:/static
    ports:
      - "0.0.0.0:80:80"

volumes:
  db_data:
  static:
