FROM python:3.6

ENV PYTHONUNBUFFERED 1

RUN mkdir /code
WORKDIR /code

ADD . /code/

RUN apt-get update

RUN pip install --upgrade pip

RUN pip install -r requirements.txt

RUN apt-get install -y postgresql postgresql-contrib


#CMD /code/run-celery.sh
